git:
  depth: false
branches:
  only:
    - master
    - organisaatio-2
language: java
jdk:
  - openjdk11
services:
  - docker
cache:
  directories:
    - $HOME/.m2
env:
  global:
    # ARTIFACTORY_USERNAME
    - secure: "JgVvhqXYLhggMP0teU7tWazk0Lh86u45KghTGKfpPbpeZANEx3/iN/jct7twd8IYsRm/VNq0eZoP42EB9ZT0F9ucjhtP/yLelyn/DoH5eYxb7uwPpaIT/ReyKRUaK5DYT7nz4q3uoApN6q5vG6Rw+joY2RLy2tjoWjoesC5rdQw="
    # ARTIFACTORY_PASSWORD
    - secure: "scvmjQm0bAg0j++hewkvHqwDzM8JBnZV4K3IML/zeuDU64TUdEgm3n5Oq1Wk3Fw4kEAAlxCAoKBBg36rRtZvfVyxbEQNN01Ye7KxKFkuqc04s+QJ0IIEq9cglU0R6JVvokGkDsByjRdyjFAgWDqK4/abkXzD4cGzFccHy46ZLLQ="
    # AWS_ACCESS_KEY_ID
    - secure: "Adnofgj5/fkiL8j7/fRk/3UHOazWn5oT82OdVPUZB1P9Ei9Fbw/HLS1UTrkIYzBjT6aBku7IRV+Y9K69uyBFFWmklkKkLQd/542QtdftGSkjFw4bnraXJu3hOD4m6uJMhYXywGbgCFtriahQJigtjxU3lYmw3TRDmu2v2pp8Zko="
    # AWS_SECRET_ACCESS_KEY
    - secure: "iDr7c8Nc5V3zHflXwYJAzkL/ObGbRzIpIxEFOoGquUWOk+04tsnmH1Aj3mztQ4G8TsHZOZ4PAIW+KtI7II9AtqyW2zRJykV/RBkAhE/nAqsFZTbYJ7lPTGxTEmD6mG4Mm2i0P2yE0fwwAD2sd3s9MpXLHScEOpOfFUKeRvYj5QA="
addons:
  sonarcloud:
    organization: "opetushallitus"
    token:
      secure: "QpZCPf2OCCcvp27AhCM4g71+OzmtdtpcPnyhhCf60/HXZB8SOSLU00qAWcv86iNLSTIuL8AVrwo+Jw63LguZTVxQ8a5Qh8SYXUgrm9i9pj66I8c/BzfhtOXQqzYLHKzl3XYqbsdfD4AVPwB5BDE1ohF1A7bPjIVvNqyjJb/bJqo="
before_install:
  - nvm install 12.18.1
  - nvm use 12.18.1
install:
  - git clone https://github.com/Opetushallitus/ci-tools.git
  - source ci-tools/common/setup-tools.sh
  - export ARTIFACT_NAME="organisaatio"
  - sudo sh -c "printf '\n%s penaali.hard.ware.fi\n' $(dig +short artifactory.opintopolku.fi|head -n1) >> /etc/hosts" # TODO: update dependencies
  - export TZ=Europe/Helsinki # TODO: fix tests

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=Opetushallitus_organisaatio -B -Dbranch=${TRAVIS_BRANCH} -Drevision=${TRAVIS_COMMIT} -DbuildNumber=${TRAVIS_BUILD_NUMBER}
  - mv organisaatio-service/target/organisaatio-service-*.war $DOCKER_BUILD_DIR/artifact/organisaatio-service.war
  - mv organisaatio-ui/target/organisaatio-ui.war $DOCKER_BUILD_DIR/artifact/organisaatio-ui.war
  - cp -vr src/main/resources/oph-configuration $DOCKER_BUILD_DIR/config/

  - export BASE_IMAGE="baseimage-war-openjdk11:master"
  - ./ci-tools/common/pull-image.sh
  - ./ci-tools/build/build-war.sh $ARTIFACT_NAME
  - ./ci-tools/build/upload-image.sh $ARTIFACT_NAME

deploy:
  - provider: script
    script: mvn deploy -pl organisaatio-api -am -DskipTests --settings ci-tools/common/maven-settings.xml
    skip_cleanup: true
    on:
      branch: master
