git:
  depth: false
branches:
  only:
    - master
    - organisaatio-2
env:
  global:
    # ARTIFACTORY_USERNAME
    - secure: "JgVvhqXYLhggMP0teU7tWazk0Lh86u45KghTGKfpPbpeZANEx3/iN/jct7twd8IYsRm/VNq0eZoP42EB9ZT0F9ucjhtP/yLelyn/DoH5eYxb7uwPpaIT/ReyKRUaK5DYT7nz4q3uoApN6q5vG6Rw+joY2RLy2tjoWjoesC5rdQw="
    # ARTIFACTORY_PASSWORD
    - secure: "scvmjQm0bAg0j++hewkvHqwDzM8JBnZV4K3IML/zeuDU64TUdEgm3n5Oq1Wk3Fw4kEAAlxCAoKBBg36rRtZvfVyxbEQNN01Ye7KxKFkuqc04s+QJ0IIEq9cglU0R6JVvokGkDsByjRdyjFAgWDqK4/abkXzD4cGzFccHy46ZLLQ="
    # AWS_ACCESS_KEY_ID
    - secure: "Adnofgj5/fkiL8j7/fRk/3UHOazWn5oT82OdVPUZB1P9Ei9Fbw/HLS1UTrkIYzBjT6aBku7IRV+Y9K69uyBFFWmklkKkLQd/542QtdftGSkjFw4bnraXJu3hOD4m6uJMhYXywGbgCFtriahQJigtjxU3lYmw3TRDmu2v2pp8Zko="
    # AWS_SECRET_ACCESS_KEY
    - secure: "iDr7c8Nc5V3zHflXwYJAzkL/ObGbRzIpIxEFOoGquUWOk+04tsnmH1Aj3mztQ4G8TsHZOZ4PAIW+KtI7II9AtqyW2zRJykV/RBkAhE/nAqsFZTbYJ7lPTGxTEmD6mG4Mm2i0P2yE0fwwAD2sd3s9MpXLHScEOpOfFUKeRvYj5QA="
    # S3 bucket used to share build files between jobs
    - s3bucket: "opintopolku-utility-travis-artifacts/artifacts/Opetushallitus/organisaatio2"
addons:
  sonarcloud:
    organization: "opetushallitus"
    token:
      secure: "QpZCPf2OCCcvp27AhCM4g71+OzmtdtpcPnyhhCf60/HXZB8SOSLU00qAWcv86iNLSTIuL8AVrwo+Jw63LguZTVxQ8a5Qh8SYXUgrm9i9pj66I8c/BzfhtOXQqzYLHKzl3XYqbsdfD4AVPwB5BDE1ohF1A7bPjIVvNqyjJb/bJqo="
before_install:
  - nvm install 12.18.1
  - nvm use 12.18.1
  - pyenv global 3.7.1
  - pip install -U pip
  - pip install awscli
  - mkdir -p ~/$TRAVIS_BUILD_NUMBER
  - aws s3 sync s3://$s3bucket/$TRAVIS_BUILD_NUMBER ~/$TRAVIS_BUILD_NUMBER
  - touch ~/$TRAVIS_BUILD_NUMBER/$TRAVIS_BUILD_NUMBER.$TRAVIS_BRANCH
  - aws s3 sync ~/$TRAVIS_BUILD_NUMBER s3://$s3bucket/$TRAVIS_BUILD_NUMBER
jobs:
  include:
    - stage: "Build & Test"
      name: "Production"
      language: java
      jdk:
        - openjdk11
      cache:
        directories:
          - $HOME/.gradle
      install:
        - sudo sh -c "printf '\n%s penaali.hard.ware.fi\n' $(dig +short artifactory.opintopolku.fi|head -n1) >> /etc/hosts" # TODO: update dependencies
        - export TZ=Europe/Helsinki # TODO: fix tests
      script:
        - echo -Dbranch=${TRAVIS_BRANCH} -Drevision=${TRAVIS_COMMIT} -DbuildNumber=${TRAVIS_BUILD_NUMBER}
        - ./gradlew clean build -Dbranch=${TRAVIS_BRANCH} -Drevision=${TRAVIS_COMMIT} -DbuildNumber=${TRAVIS_BUILD_NUMBER}
        - ./gradlew sonarqube
        - cp -R $TRAVIS_BUILD_DIR/organisaatio-service/build/libs/organisaatio-service.jar ~/$TRAVIS_BUILD_NUMBER/
        - cp -R $TRAVIS_BUILD_DIR/src/main/resources/oph-configuration ~/$TRAVIS_BUILD_NUMBER/
      after_success:
        - aws s3 sync ~/$TRAVIS_BUILD_NUMBER s3://$s3bucket/$TRAVIS_BUILD_NUMBER
    - name: "Cypress"
      language: java
      jdk:
        - openjdk11
      services:
        - postgresql
      cache:
        directories:
          - $HOME/.gradle
      install:
        - export NODE_VERSION=11.1
        - nvm install $NODE_VERSION
        - nvm use $NODE_VERSION
        - cd mock-api && npm install && cd -
        - cd organisaatio-ui && npm install && cd -
      before_script:
        - psql -c 'CREATE DATABASE organisaatio;' -U postgres
      script:
        - ./gradlew clean build -x test -Dbranch=${TRAVIS_BRANCH} -Drevision=${TRAVIS_COMMIT} -DbuildNumber=${TRAVIS_BUILD_NUMBER}
        - cd mock-api && npm run mock-api &
        - java -jar -Dspring.config.location=classpath:application.properties -Dspring.profiles.active=dev -Dspring.flyway.enabled=true -Durl-virkailija=http://localhost:9000 -Dhost.virkailija=localhost:9000 -Durl-ytj=http://localhost:9000/ytj -Durl-oidservice=http://localhost:9000/oidservice organisaatio-service/build/libs/organisaatio-service.jar &
        - cd organisaatio-ui && npm run cypress:ci
        - kill $(jobs -p) || true
    - stage: "Deploy"
      name: "release to artifactory"
      if: branch = master
      language:  java
      install:
        - echo 'override install to skip default gradle call'
      script:
        -  ./gradlew publish -PversionSuffix=.RELEASE -PsadeRepositoryUsername=$ARTIFACTORY_USERNAME -PsadeRepositoryPassword=$ARTIFACTORY_PASSWORD
      deploy:
        - provider: script
          script: echo "should deploy RELEASE $ARTIFACT_NAME"
    - name: "snapshot to artifactory"
      if: branch != master
      language:  java
      install:
        - echo 'override install to skip default gradle call'
      script:
        -  ./gradlew publish -PversionDateFormat=yyyy.MM -PsadeRepositoryUsername=$ARTIFACTORY_USERNAME -PsadeRepositoryPassword=$ARTIFACTORY_PASSWORD
      deploy:
        - provider: script
          script: echo "should deploy SNAPSHOT $ARTIFACT_NAME"
    - name: "to ecr"
      language:  java
      services:
        - docker
      install:
        - git clone https://github.com/Opetushallitus/ci-tools.git
        - export ARTIFACT_NAME="organisaatio2"
      script:
        - source ci-tools/common/setup-tools.sh
      before_deploy:
        - cp ~/$TRAVIS_BUILD_NUMBER/organisaatio-service.jar $DOCKER_BUILD_DIR/artifact/$ARTIFACT_NAME.jar
        - cp -vr ~/$TRAVIS_BUILD_NUMBER/oph-configuration $DOCKER_BUILD_DIR/config/
        - export BASE_IMAGE="baseimage-fatjar-openjdk11:master"
        - ./ci-tools/common/pull-image.sh
        - ./ci-tools/build/build-fatjar.sh $ARTIFACT_NAME
      deploy:
        - provider: script
          script: ./ci-tools/build/upload-image.sh $ARTIFACT_NAME
          on:
            all_branches: true
      after_success:
        - aws s3 rm --recursive s3://$s3bucket/$TRAVIS_BUILD_NUMBER # clean up after ourselves



