env:
  global:
    # ARTIFACTORY_USERNAME
    - secure: "JgVvhqXYLhggMP0teU7tWazk0Lh86u45KghTGKfpPbpeZANEx3/iN/jct7twd8IYsRm/VNq0eZoP42EB9ZT0F9ucjhtP/yLelyn/DoH5eYxb7uwPpaIT/ReyKRUaK5DYT7nz4q3uoApN6q5vG6Rw+joY2RLy2tjoWjoesC5rdQw="
    # ARTIFACTORY_PASSWORD
    - secure: "scvmjQm0bAg0j++hewkvHqwDzM8JBnZV4K3IML/zeuDU64TUdEgm3n5Oq1Wk3Fw4kEAAlxCAoKBBg36rRtZvfVyxbEQNN01Ye7KxKFkuqc04s+QJ0IIEq9cglU0R6JVvokGkDsByjRdyjFAgWDqK4/abkXzD4cGzFccHy46ZLLQ="
    # AWS_ACCESS_KEY_ID
    - secure: "Adnofgj5/fkiL8j7/fRk/3UHOazWn5oT82OdVPUZB1P9Ei9Fbw/HLS1UTrkIYzBjT6aBku7IRV+Y9K69uyBFFWmklkKkLQd/542QtdftGSkjFw4bnraXJu3hOD4m6uJMhYXywGbgCFtriahQJigtjxU3lYmw3TRDmu2v2pp8Zko="
    # AWS_SECRET_ACCESS_KEY
    - secure: "iDr7c8Nc5V3zHflXwYJAzkL/ObGbRzIpIxEFOoGquUWOk+04tsnmH1Aj3mztQ4G8TsHZOZ4PAIW+KtI7II9AtqyW2zRJykV/RBkAhE/nAqsFZTbYJ7lPTGxTEmD6mG4Mm2i0P2yE0fwwAD2sd3s9MpXLHScEOpOfFUKeRvYj5QA="
jobs:
  include:
    - language: java
      stage: "Build"
      name: "Production build"
      jdk:
        - openjdk11
      cache:
        directories:
          - $HOME/.gradle
          - $HOME/.cache/Cypress
          - $TRAVIS_BUILD_DIR/organisaatio-service/build/libs
          - $TRAVIS_BUILD_DIR/src/main/resources/oph-configuration
      install:
        - sudo sh -c "printf '\n%s penaali.hard.ware.fi\n' $(dig +short artifactory.opintopolku.fi|head -n1) >> /etc/hosts" # TODO: update dependencies
        - export TZ=Europe/Helsinki # TODO: fix tests
      script:
        - echo -Dbranch=${TRAVIS_BRANCH} -Drevision=${TRAVIS_COMMIT} -DbuildNumber=${TRAVIS_BUILD_NUMBER}
        - ./gradlew clean build -Dbranch=${TRAVIS_BRANCH} -Drevision=${TRAVIS_COMMIT} -DbuildNumber=${TRAVIS_BUILD_NUMBER}
    - language: java
      stage: "Test"
      name: "Cypress"
      jdk:
        - openjdk11
      services:
        - postgresql
      cache:
        directories:
          - $HOME/.gradle
          - $HOME/.cache/Cypress
          - $TRAVIS_BUILD_DIR/organisaatio-service/build/libs
      install:
        - export NODE_VERSION=11.1
        - nvm install $NODE_VERSION
        - nvm use $NODE_VERSION
        - cd mock-api && npm install && cd -
        - cd organisaatio-ui && npm install && cd -
      before_script:
        - psql -c 'CREATE DATABASE organisaatio;' -U postgres
      script:
        - cd mock-api && npm run mock-api &
        - java -jar -Dspring.config.location=classpath:application.properties -Dspring.profiles.active=dev -Dspring.flyway.enabled=true -Durl-virkailija=http://localhost:9000 -Dhost.virkailija=localhost:9000 ./organisaatio-service/build/libs/organisaatio-service.jar &
        - cd organisaatio-ui && npm run cypress:ci
        - kill $(jobs -p) || true

    - stage: "Deploy"
      name: "deploy to artifactory"
      language: java
      jdk:
        - openjdk11
      install:
        - echo 'override install to skip default gradle call'
      script:
        - echo 'override script to skip default gradle call'
      deploy:
        - provider: script
          script: echo "should deploy $ARTIFACT_NAME"
          on:
            branch: master
        ##- provider: script
        ##  script: mvn deploy -pl organisaatio-api -am -DskipTests --settings ci-tools/common/maven-settings.xml
        ##  skip_cleanup: true
        ##  on:
        ##    branch: master TODO deploy gradlella?
    - name: "push to ecr"
      language: java
      jdk:
        - openjdk11
      services:
        - docker
      cache:
        directories:
          - $TRAVIS_BUILD_DIR/organisaatio-service/build/libs
          - $TRAVIS_BUILD_DIR/src/main/resources/oph-configuration
      install:
        - git clone https://github.com/Opetushallitus/ci-tools.git
        - export ARTIFACT_NAME="organisaatio2"
      script:
        - source ci-tools/common/setup-tools.sh
      before_deploy:
        - cp organisaatio-service/build/libs/organisaatio-service.jar $DOCKER_BUILD_DIR/artifact/$ARTIFACT_NAME.jar
        - cp -vr src/main/resources/oph-configuration $DOCKER_BUILD_DIR/config/

        - export BASE_IMAGE="baseimage-fatjar-openjdk11:master"
        - ./ci-tools/common/pull-image.sh
        - ./ci-tools/build/build-fatjar.sh $ARTIFACT_NAME
      deploy:
        - provider: script
          script: ./ci-tools/build/upload-image.sh $ARTIFACT_NAME
          on:
            all_branches: true
    - stage: "Clean up cache"
      name: "Clean up cache"
      language: java
      jdk:
        - openjdk11
      install:
        - echo 'override install to skip default gradle call'
      script:
        - echo 'override script to skip default gradle call'
      cache:
        directories:
          - $HOME/.gradle
          - $HOME/.cache/Cypress
          - $TRAVIS_BUILD_DIR/organisaatio-service/build/libs
          - $TRAVIS_BUILD_DIR/src/main/resources/oph-configuration
      before_cache:
        - rm -rf $TRAVIS_BUILD_DIR/*
