version: "3"
services:
  database:
    container_name: oph-organisaatio-db
    image: postgres:13.4
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=organisaatio
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    command: ["postgres", "-c", "log_statement=all"]
volumes:
  database-data:
