spring.flyway.locations: classpath:db/migration,classpath:db/migration-test
spring.security.oauth2.resourceserver.jwt.issuer-uri: https://hahtuva.otuva.opintopolku.fi/kayttooikeus-service
spring.security.oauth2.resourceserver.jwt.jwk-set-uri: https://hahtuva.otuva.opintopolku.fi/kayttooikeus-service/oauth2/jwks
host.cas: "virkailija.hahtuvaopintopolku.fi"
host.ilb: "https://virkailija.hahtuvaopintopolku.fi"
host.virkailija: "virkailija.hahtuvaopintopolku.fi"
cluster_tarjonta_host: "alb.hahtuvaopintopolku.fi"
cluster_organisaatio_host: "alb.hahtuvaopintopolku.fi"

organisaatio.solmuluokka: "299"

feature.mockapi: false

koodisto.baseurl: "https://${host.virkailija}/koodisto-service"
viestinvalitys.baseurl: "https://viestinvalitys.hahtuvaopintopolku.fi/lahetys"
viestinvalitys.uiurl: "https://viestinvalitys.hahtuvaopintopolku.fi/raportointi"

organisaatio.tasks.datantuonti.export.enabled: true
organisaatio.tasks.datantuonti.export.bucket-name: ${export_bucket_name}

varda-rekisterointi.kayttooikeusryhma-id: 70008488
