# Base for all AWS environment configuration

rajapinnat.ytj.asiakastunnus: ${rajapinnat_ytj_asiakastunnus}
rajapinnat.ytj.avain: ${rajapinnat_ytj_avain}
organisaatio.service.username: ${organisaatio_service_username}
organisaatio.service.password: ${organisaatio_service_password}
organisaatio-service.scheduled.update.cron.expression: "0 0 1 * * ?"
ytjpaivitysloki.service.email: ${ytjpaivitysloki_service_email}
spring.datasource.url: jdbc:postgresql://${postgresql_host}:${postgresql_port}/${postgresql_db}
spring.datasource.username: ${postgresql_username}
spring.datasource.password: ${postgresql_password}

# Oletusarvoja
organisaatio-service.url: https://${host.virkailija}/organisaatio-service/

oiva.baseurl: ${oiva_baseurl}
oiva.username: ${oiva_username}
oiva.password: ${oiva_password}
