feature.mockapi: false
feature.ostj-182-uusi-osoitepalvelu: true
feature.ostj-201-muotoilematon-viesti: true

koodisto.baseurl: "https://${host.virkailija}/koodisto-service"
viestinvalitys.baseurl: "https://viestinvalitys.testiopintopolku.fi/lahetys"
viestinvalitys.uiurl: "https://viestinvalitys.testiopintopolku.fi/raportointi"

organisaatio.tasks.export.enabled: true
organisaatio.tasks.export.bucket-name: oph-yleiskayttoiset-export-pallero
organisaatio.tasks.export.copy-to-lampi: true
organisaatio.tasks.export.lampi-bucket-name: oph-lampi-qa
organisaatio.tasks.export.lampi-role-arn: ${ssm_lampi_role_arn}
organisaatio.tasks.export.lampi-external-id: ${ssm_lampi_external_id}
