host.cas: "virkailija.opintopolku.fi"
host.ilb: "https://virkailija.opintopolku.fi"
host.virkailija: "virkailija.opintopolku.fi"
cluster_tarjonta_host: "alb.opintopolku.fi"
cluster_organisaatio_host: "alb.opintopolku.fi"

feature.mockapi: false

koodisto.baseurl: "https://${host.virkailija}/koodisto-service"
viestinvalitys.baseurl: "https://viestinvalitys.opintopolku.fi/lahetys"
viestinvalitys.uiurl: "https://viestinvalitys.opintopolku.fi/raportointi"

organisaatio.tasks.export.enabled: true
organisaatio.tasks.export.bucket-name: ${export_bucket_name}
organisaatio.tasks.export.copy-to-lampi: true
organisaatio.tasks.export.lampi-bucket-name: oph-lampi-prod
organisaatio.tasks.export.lampi-role-arn: ${lampi_role_arn}
organisaatio.tasks.export.lampi-external-id: ${lampi_external_id}

varda-rekisterointi.kayttooikeusryhma-id: 107000756
