host.cas: "virkailija.opintopolku.fi"
host.ilb: "https://virkailija.opintopolku.fi"
host.virkailija: "virkailija.opintopolku.fi"
cluster_tarjonta_host: "alb.opintopolku.fi"
cluster_organisaatio_host: "alb.opintopolku.fi"

feature.mockapi: false

koodisto.baseurl: "https://${host.virkailija}/koodisto-service"
viestinvalitys.baseurl: "https://viestinvalitys.opintopolku.fi/lahetys"
viestinvalitys.uiurl: "https://viestinvalitys.opintopolku.fi/raportointi"

organisaatio.tasks.datantuonti.export.enabled: true
organisaatio.tasks.datantuonti.export.bucket-name: ${export_bucket_name}

varda-rekisterointi.kayttooikeusryhma-id: 107000756
