spring.flyway.locations: classpath:db/migration,classpath:db/migration-test
host.cas: "virkailija.testiopintopolku.fi"
host.ilb: "https://virkailija.testiopintopolku.fi"
host.virkailija: "virkailija.testiopintopolku.fi"
cluster_tarjonta_host: "alb.testiopintopolku.fi"
cluster_organisaatio_host: "alb.testiopintopolku.fi"

organisaatio.solmuluokka: "99"

feature.mockapi: false

koodisto.baseurl: "https://${host.virkailija}/koodisto-service"
viestinvalitys.baseurl: "https://viestinvalitys.testiopintopolku.fi/lahetys"
viestinvalitys.uiurl: "https://viestinvalitys.testiopintopolku.fi/raportointi"

organisaatio.tasks.datantuonti.export.enabled: true
organisaatio.tasks.datantuonti.export.bucket-name: ${export_bucket_name}

varda-rekisterointi.kayttooikeusryhma-id: 68995313
