feature.mockapi: false
feature.ostj-182-uusi-osoitepalvelu: false
feature.ostj-201-muotoilematon-viesti: false

koodisto.baseurl: "https://${host.virkailija}/koodisto-service"
viestinvalitys.baseurl: "https://viestinvalitys.opintopolku.fi/lahetys"
viestinvalitys.uiurl: "https://viestinvalitys.opintopolku.fi/"
