package fi.vm.sade.oid;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2016-08-12T14:20:13.310+03:00
 * Generated source version: 2.4.6
 */
public class ExceptionMessage extends java.lang.Exception {

    private fi.vm.sade.oid.Exception exception;

    public ExceptionMessage() {
        super();
    }

    public ExceptionMessage(String message) {
        super(message);
    }

    public ExceptionMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public ExceptionMessage(String message, fi.vm.sade.oid.Exception exception) {
        super(message);
        this.exception = exception;
    }

    public ExceptionMessage(String message, fi.vm.sade.oid.Exception exception, Throwable cause) {
        super(message, cause);
        this.exception = exception;
    }

    public fi.vm.sade.oid.Exception getFaultInfo() {
        return this.exception;
    }
}
