sudo: required
language: java
jdk:
  - openjdk11
services:
  - docker
cache:
  directories:
    - $HOME/.m2
    - $HOME/.npm
env:
  global:
    # AWS_ACCESS_KEY_ID
    - secure: "areyeVbvhiiVZ1z5zlrFxrlXpcGm4AFaJcB6zG3A/G+rOZc4zzqr1rqstnNZY3v1U5dt9t/UlRHwDTmU2Fp8uNqtz+QAS9Q4IXPbPwkZtNui07HSkVHZ4qbscLvVp8x1jQI3/gZi282y71KXnqRTUyoxhe0URVw70h/50QQwfOixgP94KfGoxby14xyZaraPCyzYygljqM1ERfMHt+Cz3DzruJmaMIOmMgHTuECWErmNzEIXF0BePmiYmRiUL5mOrRH+Uj52A+0mnodsnLwaqpN64ZbjoOdzDIudWWle7yUuw6DLxtAeDTE33U//88rQhDn0axMfhH1LqzvUG8zyvRNUimT6hgAjM5ezFhqhbuePBJ8vpLNzz9CUZ7w6QrupIie03qaQD9wjk7x6XPMNIBapzgt9+BvAaStkCJ2KAtzzx67jKuV+Ca8xARUSA663WUYm+s8ZBW3bBNBEngRIj85+ECOyfBLwQ/jjzESUZUrVv+3tOl3QQzCsiwdVaHc1LnF61Fq6hBZPBDVkRqaqm7AcoY4lL/K/BAVnFMAAEanakAz7ryRUGJtxfM4CoFywgcS3p89aN5tDHNnf9f4NwOxLyp3T4xVRaB1DnH9MqDICO3ugTsjGVroztCvaKTLjgDd08Scz95JCB4ZfzDZvrKgDUatxe39UxwCcQNxi7r0="
    # AWS_SECRET_ACCESS_KEY
    - secure: "btoD7Iu59cQJOafM3lkGUm+qN0fYMCpOJMMIluYRP6AidMmFN8mq32MLwvALKF3g3l4BWAprDeuT38zm4yb1Ib3V3srbS0+C+Govh9fvV6kxlHo/9Kv9e/MokHrywzcQfRG2+H2Vdn4Cr6YR1oT3RBNvUESkBYEc6p3kaZw2KJ/em7A1Nx8HeOl5HjBEDj/jjXFWI1z3e2DBZClEOrcjLHZpTgLj9DQlx9m6zCVcoke+VVqZKTfpmaaC6ysKR/uztqGfAE5FrPcn+1NtlrNDKMlSs1BHYt5vkU2uNJvOzksfjgzh3QA+RCNw0kbQN+qZxJ2+WqVf0BEYthWIJYqwZdQLgDXCAmkRnC1aKuaKSVaulxPeYYfISexTjwzhvE8Lo11xarEZsASN5ygcbPuvVqTzzPa+ev3ZPeAFvJViOFP4f2s9h2tihvSeCVZcBojLNcXR3r6Lm10bJCa4CQrTrNdbYw/jvn/7IzMNRCszb+1Ft9k0Fctd34Y9vmzkz0sdiM788rQ5RCDtxEq0kLBF6bi9VtQI+VgdeNGikEAYd4EoqpkNZJtDWvKfwdaV03ZzZSk6/raCCuO+kKsQ2HMeLmJdJvIpKTXgfhmwjuOPLzbO/8WJwrXDvV2fI1eRRsi7MuN9y0whEXAsihVPPMCaw2HRhhK9Yo733kQ1mGb09LU="

install:
  - git clone https://github.com/Opetushallitus/ci-tools.git
  - source ci-tools/common/setup-tools.sh
  - export ARTIFACT_NAME="varda-rekisterointi"

script:
  - ./mvnw clean install -Dbuild-number=${TRAVIS_BUILD_NUMBER} -B

  - mv target/$ARTIFACT_NAME.jar $DOCKER_BUILD_DIR/artifact/$ARTIFACT_NAME.jar
  - cp -vr oph-configuration $DOCKER_BUILD_DIR/config/

  - export BASE_IMAGE="baseimage-fatjar-openjdk11:master"
  - ./ci-tools/common/pull-image.sh
  - ./ci-tools/build/build-fatjar.sh $ARTIFACT_NAME

deploy:
  - provider: script
    script: ./ci-tools/build/upload-image.sh $ARTIFACT_NAME
    on:
      all_branches: true
