version: '3'
services:
#  varda-rekisterointi-api:
#    build: .
#    ports:
#    - "8081:8081"
  varda-rekisterointi-db:
    image: postgres:10.9
    environment:
    - POSTGRES_USER=varda-rekisterointi
    - POSTGRES_PASSWORD=varda-rekisterointi
    - POSTGRES_DB=varda-rekisterointi
    ports:
    - "5432:5432"