export const ytjHameen = (ytunnus: string) => ({
  versio: 1,
  nimi: "Hameen ammatti-instituutti Oy 4",
  ytunnus,
  yritysTunnus: {
    status: "2",
    alkupvm: "19.6.2014",
    loppupvm: "",
    yritysLopetettu: false,
    ytunnus: "2627679-5",
  },
  yritysmuoto: "Osakeyhtio",
  yritysmuotoKoodi: "16",
  toimiala: "Keskiasteen ammatillinen koulutus",
  toimialaKoodi: "85320",
  yrityksenKieli: "Suomi",
  postiOsoite: {
    katu: "PL 1010   ",
    postinumero: "13101",
    toimipaikka: "HAMEENLINNA",
    maa: "",
    kieli: 1,
  },
  kayntiOsoite: {
    katu: "VisamÃ¤entie 35 A   ",
    postinumero: "13101",
    toimipaikka: "HAMEENLINNA",
    maa: "",
    kieli: 1,
  },
  sahkoposti: "hami@hamk.fi",
  www: "https://www.hami.fi",
  puhelin: "036461",
  faksi: "036464200",
  kotiPaikka: "HÃMEENLINNA",
  kotiPaikkaKoodi: "109",
  aloitusPvm: "07.08.2014",
});
