server:
  forward-headers-strategy: native
  port: 8081
  servlet:
    context-path: /varda-rekisterointi
    session:
      timeout: 1d
      tracking-modes: cookie
      cookie:
        http-only: true
        max-age: 1d
spring:
  main:
    banner-mode: "off"
  datasource:
    url: jdbc:postgresql://localhost:${db.port:5432}/varda-rekisterointi
    username: varda-rekisterointi
    password: varda-rekisterointi
  flyway:
    out-of-order: true
  resources:
    cache:
      cachecontrol:
        no-store: true
  session:
    store-type: jdbc
varda-rekisterointi:
  url-virkailija: http://localhost:${server.port}
  url-oppija: http://localhost:${server.port}
  url-alb: http://localhost:${server.port}
  service:
    username: varda-rekisterointi
    password: varda-rekisterointi
  kayttooikeus:
    ryhma:
      paivakoti: 70008488
      ryhmaperhepaivakoti: 70008504
      perhepaivahoitaja: 70008477
