server:
  port: 8081
  servlet:
    context-path: /varda-rekisterointi
    session:
      timeout: 1d
      tracking-modes: cookie
      cookie:
        http-only: true
        max-age: 1d
spring:
  main:
    banner-mode: "off"
  datasource:
    url: jdbc:postgresql://localhost:5432/varda-rekisterointi
    username: varda-rekisterointi
    password: varda-rekisterointi
  flyway:
    out-of-order: true
  session:
    store-type: jdbc
varda-rekisterointi:
  url-virkailija: http://localhost:${server.port}
  url-tunnistus: http://localhost:${server.port}
  service:
    username: varda-rekisterointi
    password: varda-rekisterointi
