server:
  port: 8081
  servlet:
    context-path: /varda-rekisterointi
    session:
      timeout: 1d
      tracking-modes: cookie
      cookie:
        http-only: true
        max-age: 1d
spring:
  main:
    banner-mode: "off"
varda-rekisterointi:
  host-virkailija: http://localhost:${server.port}
  host-tunnistus: http://localhost:${server.port}
  service:
    username: varda-rekisterointi
    password: varda-rekisterointi
