server:
  forward-headers-strategy: native
  port: 8081
  servlet:
    context-path: /varda-rekisterointi
    session:
      timeout: 1d
      tracking-modes: cookie
      cookie:
        http-only: true
        max-age: 1d
spring:
  main:
    banner-mode: "off"
  datasource:
    url: jdbc:postgresql://localhost:5438/varda-rekisterointi
    username: varda-rekisterointi
    password: varda-rekisterointi
  flyway:
    out-of-order: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  web:
    resources:
      cache:
        cachecontrol:
          no-store: true
varda-rekisterointi:
  url-virkailija: http://localhost:${server.port}
  url-oppija: http://localhost:${server.port}
  service:
    username: varda-rekisterointi
    password: varda-rekisterointi
  kayttooikeus:
    ryhma:
      paivakoti: 70008488
      ryhmaperhepaivakoti: 70008504
      perhepaivahoitaja: 70008477
      jotpa: 1224455
  rekisterointi-ui:
    username: varda-rekisterointi
    password: varda-rekisterointi

server.tomcat.accesslog.enabled: true
server.tomcat.accesslog.directory: /dev
server.tomcat.accesslog.prefix: stdout
server.tomcat.accesslog.suffix:
server.tomcat.accesslog.file-date-format:
server.tomcat.accesslog.buffered: false
server.tomcat.accesslog.rotate: false
server.tomcat.accesslog.rename-on-rotate: false
server.tomcat.accesslog.request-attributes-enabled: true
server.tomcat.accesslog.pattern: "{\"timestamp\": \"%{yyyy-MM-dd'T'HH:mm:ss.SSSZ}t\", \"responseCode\": \"%s\", \"request\": \"%r\", \"responseTime\": \"%D\", \"requestMethod\": \"%m\", \"service\": \"varda-rekisterointi\", \"environment\": \"${env.name}\", \"customer\": \"OPH\", \"user-agent\": \"%{User-Agent}i\", \"caller-id\": \"%{Caller-Id}i\", \"clientSubSystemCode\": \"%{clientSubSystemCode}i\", \"x-forwarded-for\": \"%{X-Forwarded-For}i\", \"x-real-ip\": \"%{X-Real-IP}i\", \"remote-ip\": \"%a\", \"session\": \"%{JSESSIONID}c\", \"response-size\": \"%B\", \"referer\": \"%{Referer}i\", \"opintopolku-api-key\": \"%{Opintopolku-Api-Key}i\"}"
