name: dependabot-vulnerability-alert

on:
  pull_request_target:
    types: [opened]

jobs:
  create-alert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: "master"
      - name: Send Slack alert if PR created by dependabot
        if: github.base_ref == 'master' && github.actor == 'dependabot[bot]'
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"channel": "#yleiskäyttöiset-alerts", "icon_emoji": ":warning:", "text": "*${{ github.repository }}:*\nDependabot created a new PR"}' ${{ secrets.SLACK_WEBHOOK_URL }}
