const REKISTEROINTI_HOSTNAME = process.env.REKISTEROINTI_HOSTNAME || 'localhost';
const REKISTEROINTI_PORT = process.env.REKISTEROINTI_PORT || 3000;
export const REKISTEROINTI_URL = `http://${REKISTEROINTI_HOSTNAME}:${REKISTEROINTI_PORT}`;
