<?xml version='1.0' encoding='UTF-8'?>
<?xml-stylesheet type="text/xsl" href="../../../../../../../build-parent/trunk/build-utilities/src/main/resources/wsdl2html-oph.xsl"?>
<wsdl:definitions name="koulutustarjoajaPublicService"
                  targetNamespace="http://service.tarjoaja.sade.vm.fi"
                  xmlns:ns1="http://service.tarjoaja.sade.vm.fi/types"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:tns="http://service.tarjoaja.sade.vm.fi"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <wsdl:types>
        <xsd:schema targetNamespace="http://service.tarjoaja.sade.vm.fi">
            <xsd:import namespace="http://service.tarjoaja.sade.vm.fi/types" schemaLocation="koulutustarjoajaService.xsd" />
        </xsd:schema>
    </wsdl:types>

    <wsdl:message name="findByOrganizationOidRequest">
        <wsdl:part element="ns1:findByOrganizationOidRequest" name="parameters">
        </wsdl:part>
    </wsdl:message>

    <wsdl:message name="findByOrganizationOidResponse">
        <wsdl:part element="ns1:findByOrganizationOidResponse" name="parameters"></wsdl:part>
    </wsdl:message>

    <wsdl:message name="genericFault">
		<wsdl:part name="fault" element="ns1:genericFaultInfo"></wsdl:part>
	</wsdl:message>

    <!-- Operations -->
    <wsdl:portType name="KoulutustarjoajaPublicService">
        <wsdl:documentation>
            LOP (Learning Opportunity Provider) tiedon hallintaan.
        </wsdl:documentation>
        <wsdl:operation name="findByOrganizationOid">
            <wsdl:documentation>
                Lataa LOP-metadatan Organisaation OID:lla.
            </wsdl:documentation>
            <wsdl:input message="tns:findByOrganizationOidRequest" name="findByOrganizationOidRequest">
            </wsdl:input>
            <wsdl:output message="tns:findByOrganizationOidResponse" name="findByOrganizationOidResponse">
            </wsdl:output>
            <wsdl:fault name="fault" message="tns:genericFault"></wsdl:fault>
        </wsdl:operation>
    </wsdl:portType>

    <wsdl:binding name="KoulutustarjoajaPublicServiceSoapBinding" type="tns:KoulutustarjoajaPublicService">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
        <wsdl:operation name="findByOrganizationOid">
            <soap:operation soapAction="" style="document" />
            <wsdl:input name="findByOrganizationOidRequest">
                <soap:body use="literal" />
            </wsdl:input>
            <wsdl:output name="findByOrganizationOidResponse">
                <soap:body use="literal" />
            </wsdl:output>
        </wsdl:operation>

    </wsdl:binding>

    <wsdl:service name="KoulutustarjoajaPublicService">
        <wsdl:port name="KoulutustarjoajaPublicServicePort" binding="tns:KoulutustarjoajaPublicServiceSoapBinding">
            <soap:address location="http://localhost:8181/cxf/koulutustarjoajaPublicService" />
        </wsdl:port>
    </wsdl:service>

</wsdl:definitions>
