server.servlet.session.cookie.domain: untuvaopintopolku.fi

url-oppija:  https://untuvaopintopolku.fi
url-virkailija: https://virkailija.untuvaopintopolku.fi
url-rekisterointi: https://rekisterointi.untuvaopintopolku.fi

rekisterointi.valtuudet.host: "https://asiointivaltuustarkastus.test.suomi.fi"
