server.servlet.session.cookie.domain: hahtuvaopintopolku.fi

url-oppija:  https://hahtuvaopintopolku.fi
url-virkailija: https://virkailija.hahtuvaopintopolku.fi
url-rekisterointi: https://rekisterointi.hahtuvaopintopolku.fi
url-alb: hahtuvaopintopolku.fi

rekisterointi.valtuudet.host: "https://asiointivaltuustarkastus.test.suomi.fi"
varda-rekisterointi.url: https://virkailija.hahtuvaopintopolku.fi/varda-rekisterointi/api/rekisterointi
