server.servlet.session.cookie.domain: testiopintopolku.fi

url-oppija:  https://testiopintopolku.fi
url-virkailija: https://virkailija.testiopintopolku.fi
url-rekisterointi: https://rekisterointi.testiopintopolku.fi

rekisterointi.valtuudet.host: "https://asiointivaltuustarkastus.test.suomi.fi"
