server.servlet.session.cookie.domain: testiopintopolku.fi

url-oppija:  https://testiopintopolku.fi
url-virkailija: https://virkailija.testiopintopolku.fi
url-rekisterointi: https://rekisterointi.testiopintopolku.fi
url-alb: testiopintopolku.fi

varda-rekisterointi.valtuudet.host: "https://asiointivaltuustarkastus.test.suomi.fi"
varda-rekisterointi.url: https://virkailija.testiopintopolku.fi/varda-rekisterointi/api/rekisterointi
