server:
    port: 8080
    servlet:
        session:
            timeout: 1h
            cookie:
                secure: true
                max-age: 1h
    tomcat:
        port-header: X-Real-Port
        protocol-header: X-Real-Proto
rekisterointi:
    service:
        username: ${varda_rekisterointi_service_username}
        password: ${varda_rekisterointi_service_password}
    valtuudet:
        client-id: ${varda_rekisterointi_valtuudet_client_id}
        api-key: ${varda_rekisterointi_valtuudet_api_key}
        oauth-password: ${varda_rekisterointi_valtuudet_oauth_password}
varda-rekisterointi:
    username: ${varda_rekisterointi_rekisterointi_ui_username}
    password: ${varda_rekisterointi_rekisterointi_ui_password}