server:
    port: 8080
    servlet:
        session:
            timeout: 1h
            cookie:
                secure: true
                max-age: 1h
    tomcat:
        port-header: X-Real-Port
        protocol-header: X-Real-Proto
spring:
    data:
        redis:
            port: 6379
    session:
        store-type: redis
        redis:
            flush-mode: on_save
            namespace: spring:session