host_oppija: untuvaopintopolku.fi
host_virkailija: virkailija.untuvaopintopolku.fi

varda-rekisterointi.schedule.kunta-email-task: "FIXED_DELAY|3600s"
varda-rekisterointi.schedule.raportoi-epaonnistumiset-task: "FIXED_DELAY|300s"
varda-rekisterointi.valtuudet.host: "https://asiointivaltuustarkastus.test.suomi.fi"

varda-rekisterointi.kayttooikeus.ryhma.paivakoti: 70008488
varda-rekisterointi.kayttooikeus.ryhma.ryhmaperhepaivakoti: 70008504
varda-rekisterointi.kayttooikeus.ryhma.perhepaivahoitaja: 70008477
varda-rekisterointi.kayttooikeus.ryhma.jotpa: 70492916