name: varda-rekisterointi
on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
jobs:
  build:
    services:
      postgres:
        image: postgres:15.7@sha256:68b988a164c8bdf0752fa7a4ae2d4b34a058e21c6327e69f741c081a38e97254
        ports:
          - 5439:5432
        env:
          POSTGRES_USER: varda-rekisterointi
          POSTGRES_DB: varda-rekisterointi
          POSTGRES_PASSWORD: varda-rekisterointi
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: varda-rekisterointi/package-lock.json
      - name: Build frontend
        working-directory: ./varda-rekisterointi
        run: |
          npm ci
          npm run lint
          npm test
          npm run build
      - uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: 'maven'
      - name: Maven version
        run: mvn --version
      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ./varda-rekisterointi
        run: mvn clean install -B -Dbranch=$GITHUB_REF_NAME -Drevision=$GITHUB_SHA -DbuildNumber=$GITHUB_RUN_NUMBER/$GITHUB_RUN_ATTEMPT
      - name: Upload varda-rekisterointi-jar
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4
        with:
          name: varda-rekisterointi-jar
          path: target/varda-rekisterointi.jar