name: Build and test artifacts
on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  run-frontend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./scripts/ci/run-frontend-tests.sh
  run-rekisterointi-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./scripts/ci/run-rekisterointi-tests.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  run-java-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./scripts/ci/run-java-tests.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  run-rekisterointi-java-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./scripts/ci/run-varda-rekisterointi-java-tests.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  run-playwright-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./scripts/ci/run-playwright-tests.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright/playwright-report/
          retention-days: 30

